#ifndef _BRUNODEA_CG_T3_MAXROS_H_
#define _BRUNODEA_CG_T3_MAXROS_H_

#define WINDOW_WIDTH 600
#define WINDOW_HEIGHT 480

#define MODELVIEW ModelViewMatrixStack::instance()
#define PI 3.14159265

#define SIDEBAR_WIDTH 150
#define SIDEBAR_HEIGHT WINDOW_HEIGHT

#define CANVAS_WIDTH (WINDOW_WIDTH - SIDEBAR_WIDTH)
#define CANVAS_HEIGHT WINDOW_HEIGHT

//#define PERSPECTIVE PROJECTION::perpective(45.f, (float)CANVAS_WIDTH/(float)CANVAS_HEIGHT, 0.1, 1000)
#define PROJECTION Projection::instance()

#endif